### ISSUE TITLE
Import-Module -Name HPESmartArrayCmdlets

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#18]
Hi,
If i use this construct in script, i always see License screen and must Accept by mouse-click. This isn't usable for automatization.
Do you have some way how manage it?
Reinstall and some similar i try.
Thanks
Ari

**Comment by hp-powershell** [comment]
Hi Ari,

Thanks for writing to PowerShell team.
We suspect that the multiple license popups are prompted since the cmdlets are not being executed in administrative mode.

Kindly try executing them on a PowerShell window opened in administrative mode. One time accepting of license prompt is required.
Let us know if you have any further query .

Thanks & Regards,
PowerShell Team
