### ISSUE TITLE
HPEOACmdlets 2.0.0.0 is not compatible with HPEiLOCmdlets v2.2.0.0

### ISSUE THREAD

**Issue by AleksejsC** [HewlettPackard/PowerShell-ProLiant-SDK#23]
Hello!
While trying to execute Invoke-HPEOAiLOCommand I'm getting error:
`This cmdlet only supports HPiLOCmdlets version 1.2.0.0 or later. Install HPiLOCmdlets version 1.2.0.0 or later and try again.`
But I have HPEilocmdlets v2.2.0.0 installed.

**Comment by hp-powershell** [comment]
Hi,

This behavior is by design in iLO 2.0 and above.
2.x uses Redfish interfaces and RIBCL is required for the Invoke cmdlet to execute in OA context which is now by design changed.

You can use iLO 1.5.0.0 along with OA 2.0.0.0 if required.

Let us know in case of any further query.

Thanks & Regards,
Powershell Team
