### ISSUE TITLE
ILO 5 (1.40 and above) Security Dashboard configure alerts with powershell

### ISSUE THREAD

**Issue by Michel-CO** [HewlettPackard/PowerShell-ProLiant-SDK#32]
Hi,
we are currently creating a configuration script for ILO.
The new firmware version 1.40 and newer comes with the new Security Dashboard. This shows errors as default.
We want to fix these errors with Powersell script. We use the latest HPE ILO CMDLets 2.2.0.0.
The following errors appear:
-Require Login for iLO RBSU
-Secure boat
-Password Complexity

We change the setting "Require Login for iLO RBSU" with the following powershell command: "$ ILOConnection | Set-HPEiLOAccessSetting -RequiredLoginForiLORBSU Yes"
We can not turn off the "Secure Boot" setting because our servers were installed with the "Legacy" setting and are running. Thus, we can not switch to UEFI including Secure Boot during operation.

The security dashboard must ignore with Powershell command this error:
$ ILOConnection | Enable-HPEiLOSecurityDashboardSetting -IgnoreSecureBoot

We also want to fix the "Password Complexity" error, but I can not find any way to do this through Powershell.
A workaround would be currently only to set an ignore in the security dashboard:
$ ILOConnection | Enable-HPEiLOSecurityDashboardSetting -IgnorePasswordComplexity

How can we configure Password Complexity with Powershell?

Michel

**Comment by hp-powershell** [comment]
Hi Michel,

This is currently not supported in HPEiLOCmdlets. This will be fixed in the next release. 

As a workaround you can use Redfish cmdlets that is available in the Powershell gallery.

PS C:\Windows\system32> $session= Connect-HPERedfish -Address <IP> -Username <UN> -Password <PWD> -DisableCertificateAuthentication

PS C:\Windows\system32>   $hpe = @{}
            $hpe.Add('EnforcePasswordComplexity',$false)
        
            $oem = @{}
            $oem.Add('Hpe',$hpe)
    
            $pwdComplexity= @{}
            $pwdComplexity.Add('Oem',$oem)
 
PS C:\Windows\system32>$result = Set-HPERedfishData -Odataid '/redfish/v1/AccountService/' -Setting $pwdComplexity -Session $session -DisableCertificateAuthentication

Thanks,
Hema
