### ISSUE TITLE
iLO5 support for Set-HPEiLOKerberosConfig

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#37]
Hi,
This cmdlet have support only for iLO4. Can you add support for iLO5 please?

Thanks

**Comment by hp-powershell** [comment]
Hi,

Kerberos support for iLO5 will be given in the next release.

Thanks,
Hema

**Comment by TSoucek** [comment]
But it behave very strange for iLO 5:
1) parameter KeyTab it is no longer content of KeyTab but URL
2) if port provided as parameter it add port to KTABserver address (server.domain:port), not only configure port
3) if only port is provided nothing happen, looks like completely ignored
4) example with "both iLO4 and iLO5" does not work as KeyTab for iLO4 does not work as value for iLO5
5) no idea about structure of KeyTab file for iLO5

**Comment by derco0n** [comment]
So more than 2 years later i'm trying to find out what is different since iLO4.
It seems that keytab-files can be set using Set-HPEiLOKerberosConfig for iLO4 with the keytab-file encoded ba64 in a PEM-like style:

```
"-----BEGIN KEYTAB-----
$keytabBase64string
-----END KEYTAB-----"
```

However, this doesn't work with iLO5 and above.
The redfish-API now seems to expect a URL to a keytab-file instead of base64-encoded data. But when throwing a URL as "-Keytab" the response complains about an "InvalidObject"

```
VERBOSE: [Set-HPEiLOKerberosConfig][someserver.mylocaldomain.com][Redfish]: Redfish response message: InvalidObject
```

So what exactly is the correct format?
How can the HPEiLOCmdlets be used to Upload a Keytab-file to iLO5 and -6 boards?
