### ISSUE TITLE
Import-HPEiLOLDAPCACertificate Required Property Missing

### ISSUE THREAD

**Issue by grimsrue** [HewlettPackard/PowerShell-ProLiant-SDK#52]
Hello HP,

Any news on when the next HPEILOCMDlets version release? I read in another post that 3.0.0.1 was suppose to fix the issue of the missing Required Property error for the Import-HPEiLOLDAPCACertificate cmdlet. Still seeing the same issue. I need to update 290 servers. 

Also......
I found that I cannot get cmdlets Update-HPEiLOFirmware and Add-HPEiLODirectoryGroup when running 2.30 or higher of the iLO5 firmware. Not sure if anyone else is having the same issue or not

One other weird issue. Not sure if its by design or not. I cant add more that one Directory Group with the "Recovery Set" option set to "Yes" with cmdlet Add-HPEiLODirectoryGroup. I have to add my Directory groups first, THEN got back with Set-HPEiLODirectoryGroup to check "Recovery Set" on all the groups that were just created.

**Comment by hp-powershell** [comment]
Hi ,

HPiLOCmdlets 3.0.0.1 does fix the import certificate issue but iLO FW 2.30 has introduced a new Breaking redfish URI change which in order for it to get reflected in the powershell cmdlets , Cmdlets need to undergo changes and incorporate the changes made by iLO FW . This new redfish change introduced by iLO is a major change . 

Powershell team is currently working on enabling iLO FW 2.30 and the new release 3.1 will be planned with the iLO FW 2.30 support.

Thanks & Regards,
Powershell Team

**Comment by ariael** [comment]
Hi.
What? "new release 3.1 will be planned with the iLO FW 2.30 support." This is sure not true. 
We have to use iLO 2.30 from release date, because HP support heavy insist on use iLO 2.30!!!
And argument that our production automatization collapsed HP ignore. I push several month to HP and his developer for change - and nothing. And we are not small customer - one og the biggest of the world! No one care. And now we are realy 2 month without working automatization...

**Comment by hp-powershell** [comment]
Hi ,

I understand the inconvenience caused here due to this issue. We have fast tracked our release process in order to get the release out ASAP . 

Powershell version releases are usually trailing releases with iLO FW releases . We are having plans to change this too in future and make it inline. But for now since iLO FW 2.30 has introduced a major code change in redfish uri format we are seeing this issue were backward compatibility got effected . This is a very rare case and wouldn't be seen always . Kindly be assured that this wouldn't be the case going forward.

We are taking this as our top most priority and we are working on making the release sooner .

Thanks & Regards,
HPE Powershell Team

**Comment by hp-powershell** [comment]
Hi ,

The new version HPEiLOCmdlets 3.1 is live now and available to download from Powershell Gallery and also the HPE support portal . 

Kindly upgrade and let us know if any findings . 

Thanks & Regards,
Powershell Team
