### ISSUE TITLE
iLO5 Scripting Tools issues for ver. 2.30 and later

### ISSUE THREAD

**Issue by VVic27** [HewlettPackard/PowerShell-ProLiant-SDK#58]
Hello,
I hope this information is going to help other people facing same issue.
To understand better my frustration I need to briefly explain the situation: I got the task to apply specific iLO and BIOS settings for 140 HPE DL360 and DL380 servers. The only settings that had been already configured were iLO IPv4 settings.
So I built a PowerShell script to apply all required iLO and BIOS settings. Surprisingly I was getting inconsistent results.
After spending a lot of time on troubleshooting, I realized there are issues with the powershell commands. Who would expect this!
I have double checked again the User Guides, Release Notes and GitHut comments. I wasn't able to find any kind of information about this issue.
Next, I raised a case with HPE and after 10 working days I got below reply from L2 support acknowledging there are issues with iLOCmdlets starting with iLO version 2.30:
“There has been some major changes and enhancements that was made in iLO 2.30 and later. In order to support them, the power shell cmdlets are also required to undergo some changes. However since the latest version of iLOCmdlets 3.0.0.1 is released prior to iLO FW 2.30 hence doesn’t have the changes incorporated already. 
This has been already taken in to consideration and it is expected to be fixed in the next release version of the HPEiLOCmdlets.  
Release ETA is possibly about in a month."
This is disappointing and kind of mind blowing since iLO5 version 2.30 (which includes the enhancements) was released 5 months ago.
If the developers knew about the enhancements why there is no notification for HPEiLOCmdlets 3.0.0.1?!
Cheers

**Comment by hp-powershell** [comment]
Hi ,

Thanks for writing to us . 

To clarify few queries you have raised ,Powershell team was not notified about the change which iLO team introduced, prior to iLO FW 2.30 release as powershell releases have always been trailing releases after the iLO team releases. In our previous structure Support for a iLO FW comes post iLO releases that FW which we are changing now by bringing in a change to release Powershell cmdlets matching the iLO FW release .  

Also the reason why support to FW 2.30 is taking much longer time is because of the number of cmdlets which are effected by the iLO FW introduced change . There were more than 70 cmdlets which had to be rewritten from scratch for them to work also testing need to be done full fledged in order for having a smooth build rolled out which can then be used by all without any further glitches. 

We have taken the release of HPEiLOCmdlets 3.1 over all our other priority works and we will be having the release done prior to Feb 19th . 
We have enabled new features too which have come in iLO FW 2.30 in this release. 

Thanks for understanding. 

Thanks & Regards,
Powershell Team

**Comment by PonchoHobono** [comment]
Is this still on pace to be released in 2 days?

**Comment by hp-powershell** [comment]
Hi,

Yes. You should be able to upgrade to newer version by early next week. 

Thanks for understanding . 

Thanks & Regards,
Powershell Team

**Comment by markjamesbaker** [comment]
Hi,

It was previously stated that HPEiLOCmdlets 3.1 would be having its release prior to Feb 19th, but it looks like that date has slipped.

Do you have a revised release date?

**Comment by hp-powershell** [comment]
Hi ,

Thanks for writing to us . 

The new version HPEiLOCmdlets 3.1 is live now and available to download from Powershell Gallery and also the HPE support portal . 

Kindly upgrade and let us know if any findings . 

Thanks & Regards,
Powershell Team
