### ISSUE TITLE
Connecting to HPE Synergy Gen 10 Plus doesn't work

### ISSUE THREAD

**Issue by fonta** [HewlettPackard/PowerShell-ProLiant-SDK#79]
Trying to connect to iLO of some Synergy 480 Gen10 Plus servers, but this fails.

Error: Connect-HPEiLO : [fqdn] : Server Information could not determined for EISA ID: $0E110872

Connecting to non-plus servers works.

**Comment by Tricky4069** [comment]
I also have the same issue, using the latest V3.2 HPEiLO cmdlets. 
Same Synergy frame, same iLO 5 firmware versions - I42 ROM works fine (Gen 10) but not the I44 ROM (Gen 10 Plus).
The iLO Cmdlet release notes for V3.0.0.0 states support for Gen 10 Plus - https://support.hpe.com/connect/s/softwaredetails?language=en_US&softwareId=MTX_9fad098b0eda492c9ca86eb946&tab=revisionHistory

**Comment by hp-powershell** [comment]
Hi ,

We see there is eisa id in error , i.e this server is not enabled yet in code .
By design our cmdlets are enabled on proliant servers and enablement on other servers are request based from respective server family management . 

We will bring this to management notice and let know the discussion points . 

Thanks & Regards,
Powershell Team

**Comment by Tricky4069** [comment]
It was fixed for my gen10 Plus servers in the 3.3 release.

**Comment by hp-powershell** [comment]
Hi 

Kindly verify with the latest version of HPEiLOCmdlets . 
We see that the EisaID is already part of our codebase . 

Thanks & Regards,
Powershell Team
