### ISSUE TITLE
Get-HPEILOHealthSummary with ILO5 Firmware 2.72

### ISSUE THREAD

**Issue by Michel-CO** [HewlettPackard/PowerShell-ProLiant-SDK#81]
Hi,
i test the new ILO5 firmware with some scripts from us. Now i found a strange error, when i use the command Get-HPEiLOHealthSummary (HPE-ILO Module Version 3.3.0.0):

[Get-HPEiLOHealthSummary : [iloFQDN]: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'HPE.iLO.Communication.Redfish.DataEntity.OData' because the type requires 
a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) 
like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'Oem.Hpe.Links.PCIDevices', line 1, position 4909.
At line:1 char:8
+ $con | Get-HPEiLOHealthSummary
+        ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Get-HPEiLOHealthSummary], Exception
    + FullyQualifiedErrorId : HPE.iLO.Cmdlet.GetHPEiLOHealthSummary]

This error only show at new firmware ILO 2.72.

Can you reproduce and fix this?

**Comment by JoMontel** [comment]
You are not alone.

Get-HPEiLOHealthSummary : [x.x.x.x]: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type
'HPE.iLO.Communication.Redfish.DataEntity.OData' because the type requires a JSON object (e.g. {"name":"value"}) to
deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to
an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be
deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a
JSON array.
Path 'Oem.Hpe.Links.PCIDevices', line 1, position 5879.
At C:\Scripts\BareMetalDeployment\05_MainScript\New_BareMetalSynergyServer_v3.4.ps1:119 char:15
+ ...   $status = Get-HPEiLOHealthSummary -Connection $iloConnection -Warni ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Get-HPEiLOHealthSummary], Exception
    + FullyQualifiedErrorId : HPE.iLO.Cmdlet.GetHPEiLOHealthSummary

This needs to be addressed, as it is preventing us from deploying ESX on a wide scale.

Lines used:
$iloConnection = Connect-HPEiLO -IP $iLOIPaddress -Username $iloUsername -Password ($DecriptIloPassword).GetNetworkCredential().password -DisableCertificateAuthentication #-WarningAction SilentlyContinue -Verbose:$false -ErrorAction SilentlyContinue

$status = Get-HPEiLOHealthSummary -Connection $iloConnection -WarningAction SilentlyContinue #-ErrorAction SilentlyContinue -Verbose:$false

**Comment by hp-powershell** [comment]
hi ,

This issue is fixed in our upcoming release HPEiLOCmdlets 4.0 which is scheduled for Jan next year .

Thanks & Regards,
Powershell Team

**Comment by klaspihl** [comment]
> hi ,
> 
> This issue is fixed in our upcoming release HPEiLOCmdlets 4.0 which is scheduled for Jan next year .
> 
> Thanks & Regards, Powershell Team

@hp-powershell , Do you have a release date on version 4.0`?

**Comment by Michel-CO** [comment]
HPE released the new CMDLets:
https://support.hpe.com/connect/s/softwaredetails?language=de&softwareId=MTX_bb648dcdf9b9424b8ffdd96d53
